/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ep Digital Design (https://sketchfab.com/Epdigitaldesign)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wireframe-3d-globe-20adb20e73ee4b68bc1207e1675b8891
Title: Wireframe 3D Globe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Wireglobe = (props)=> {
  const { nodes, materials } = useGLTF('/models/wireframe_3d_globe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['Material.001']}
        rotation={[Math.PI /2, 0, Math.PI]}
        scale={0.05}
        emissive={[1, 1, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/wireframe_3d_globe.glb')

export default Wireglobe